default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: manidweep_development

test:
  <<: *default
  database: manidweep_test

production:
  <<: *default
  database: manidweep_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
